// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmu3ZlTCX6ULnNDxUblkJMssbUisSH5-k',
    appId: '1:842775331840:web:ef931c812d472f5100c4e5',
    messagingSenderId: '842775331840',
    projectId: 'morpheus-334e6',
    authDomain: 'morpheus-334e6.firebaseapp.com',
    storageBucket: 'morpheus-334e6.firebasestorage.app',
    measurementId: 'G-YPC75J215V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5VBEu4lnFOV9Wwr6dWdOgy-m5UXYElcU',
    appId: '1:842775331840:android:66da62adf93ccd0000c4e5',
    messagingSenderId: '842775331840',
    projectId: 'morpheus-334e6',
    storageBucket: 'morpheus-334e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARSItZ_AdziZs3JtSfZ9DxyvKZ9xCdT2w',
    appId: '1:842775331840:ios:c0b5a1fb17d5656900c4e5',
    messagingSenderId: '842775331840',
    projectId: 'morpheus-334e6',
    storageBucket: 'morpheus-334e6.firebasestorage.app',
    androidClientId:
        '842775331840-mqkeg9of6v64284ctemuejh4do7aajai.apps.googleusercontent.com',
    iosClientId:
        '842775331840-vom74nr61km2rdetvu1bkt3kv30pha5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.morpheus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARSItZ_AdziZs3JtSfZ9DxyvKZ9xCdT2w',
    appId: '1:842775331840:ios:c0b5a1fb17d5656900c4e5',
    messagingSenderId: '842775331840',
    projectId: 'morpheus-334e6',
    storageBucket: 'morpheus-334e6.firebasestorage.app',
    androidClientId:
        '842775331840-mqkeg9of6v64284ctemuejh4do7aajai.apps.googleusercontent.com',
    iosClientId:
        '842775331840-vom74nr61km2rdetvu1bkt3kv30pha5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.morpheus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmu3ZlTCX6ULnNDxUblkJMssbUisSH5-k',
    appId: '1:842775331840:web:8bc1dd4fe957557e00c4e5',
    messagingSenderId: '842775331840',
    projectId: 'morpheus-334e6',
    authDomain: 'morpheus-334e6.firebaseapp.com',
    storageBucket: 'morpheus-334e6.firebasestorage.app',
    measurementId: 'G-DC7VQ2C51M',
  );
}
